/**
 * Token references — string values that resolve to the CSS variables in
 * tokens.css at runtime. Use these in inline styles, prop defaults, or
 * anywhere CSS variables work.
 *
 *   <div style={{ background: tokens.color.button.primaryDefault }} />
 *
 * The CSS file (`./tokens.css`) is the source of truth for the *values*.
 */

export const tokens = {
  color: {
    background: {
      active: "var(--background-active)",
      altNegative: "var(--background-alt-negative)",
      altNegativeBase: "var(--background-alt-negative-base)",
      brandBase: "var(--background-brand-base)",
      brandSubdued: "var(--background-brand-subdued)",
      default: "var(--background-default)",
      defaultInverse: "var(--background-default-inverse)",
      disabled: "var(--background-disabled)",
      element: "var(--background-element)",
      hover: "var(--background-hover)",
      negative: "var(--background-negative)",
      negativeBase: "var(--background-negative-base)",
      notice: "var(--background-notice)",
      noticeBase: "var(--background-notice-base)",
      positive: "var(--background-positive)",
      positiveBase: "var(--background-positive-base)",
      secondary: "var(--background-secondary)",
      selected: "var(--background-selected)",
    },
    border: {
      altNegative: "var(--border-alt-negative)",
      base: "var(--border-base)",
      brand: "var(--border-brand)",
      disabled: "var(--border-disabled)",
      emphasis: "var(--border-emphasis)",
      negative: "var(--border-negative)",
      notice: "var(--border-notice)",
      positive: "var(--border-positive)",
      subtle: "var(--border-subtle)",
    },
    content: {
      altNegative: "var(--content-alt-negative)",
      base: "var(--content-base)",
      baseInverse: "var(--content-base-inverse)",
      brandInverse: "var(--content-brand-inverse)",
      brandPrimary: "var(--content-brand-primary)",
      disabled: "var(--content-disabled)",
      emphasis: "var(--content-emphasis)",
      emphasisInverse: "var(--content-emphasis-inverse)",
      info: "var(--content-info)",
      linkActive: "var(--content-link-active)",
      linkDefault: "var(--content-link-default)",
      linkHover: "var(--content-link-hover)",
      negative: "var(--content-negative)",
      notice: "var(--content-notice)",
      placeholder: "var(--content-placeholder)",
      positive: "var(--content-positive)",
      subtle: "var(--content-subtle)",
      subtleInverse: "var(--content-subtle-inverse)",
    },
    button: {
      accentActive: "var(--button-accent-active)",
      accentContent: "var(--button-accent-content)",
      accentDefault: "var(--button-accent-default)",
      accentHover: "var(--button-accent-hover)",
      destructiveActive: "var(--button-destructive-active)",
      destructiveDefault: "var(--button-destructive-default)",
      destructiveHover: "var(--button-destructive-hover)",
      disabled: "var(--button-disabled)",
      primaryActive: "var(--button-primary-active)",
      primaryDefault: "var(--button-primary-default)",
      primaryHover: "var(--button-primary-hover)",
    },
    overlay: {
      default25: "var(--overlay-default-25)",
      default50: "var(--overlay-default-50)",
      inverse50: "var(--overlay-inverse-50)",
    },
  },
  space: {
    0: "var(--space-0)",
    1: "var(--space-1)",
    2: "var(--space-2)",
    3: "var(--space-3)",
    4: "var(--space-4)",
    5: "var(--space-5)",
    6: "var(--space-6)",
    7: "var(--space-7)",
    8: "var(--space-8)",
  },
  radius: {
    sm: "var(--radius-sm)",
    md: "var(--radius-md)",
    lg: "var(--radius-lg)",
    xl: "var(--radius-xl)",
    full: "var(--radius-full)",
  },
  font: {
    sans: "var(--font-sans)",
    mono: "var(--font-mono)",
    weight: {
      regular: "var(--font-weight-regular)",
      medium: "var(--font-weight-medium)",
    },
  },
  tracking: {
    tight: "var(--tracking-tight)",
    sm: "var(--tracking-sm)",
  },
  text: {
    xs: "var(--text-xs)",
    sm: "var(--text-sm)",
    base: "var(--text-base)",
    l: "var(--text-l)",
    xl: "var(--text-xl)",
    "2xl": "var(--text-2xl)",
    "3xl": "var(--text-3xl)",
    "4xl": "var(--text-4xl)",
    "5xl": "var(--text-5xl)",
  },
  leading: {
    xs: "var(--leading-xs)",
    sm: "var(--leading-sm)",
    md: "var(--leading-md)",
    lg: "var(--leading-lg)",
    xl: "var(--leading-xl)",
    "2xl": "var(--leading-2xl)",
    "3xl": "var(--leading-3xl)",
    "4xl": "var(--leading-4xl)",
    "5xl": "var(--leading-5xl)",
  },
  type: {
    heading: {
      "5xl": "var(--type-heading-5xl)",
      "4xl": "var(--type-heading-4xl)",
      "3xl": "var(--type-heading-3xl)",
      "2xl": "var(--type-heading-2xl)",
      xl: "var(--type-heading-xl)",
      l: "var(--type-heading-l)",
      m: "var(--type-heading-m)",
      s: "var(--type-heading-s)",
      xs: "var(--type-heading-xs)",
      tracking: "var(--tracking-tight)",
    },
    paragraph: {
      lMedium: "var(--type-paragraph-l-medium)",
      lRegular: "var(--type-paragraph-l-regular)",
      mMedium: "var(--type-paragraph-m-medium)",
      mRegular: "var(--type-paragraph-m-regular)",
      sMedium: "var(--type-paragraph-s-medium)",
      sRegular: "var(--type-paragraph-s-regular)",
      xsMedium: "var(--type-paragraph-xs-medium)",
      xsRegular: "var(--type-paragraph-xs-regular)",
      tracking: "var(--tracking-sm)",
    },
  },
  motion: {
    easeOut: "var(--ease-out)",
    easeIn: "var(--ease-in)",
    easeInOut: "var(--ease-in-out)",
    easeOvershoot: "var(--ease-overshoot)",
    durationFast: "var(--duration-fast)",
    durationBase: "var(--duration-base)",
    durationSlow: "var(--duration-slow)",
    enterFast: "var(--motion-enter-fast)",
    enter: "var(--motion-enter)",
    enterSlow: "var(--motion-enter-slow)",
    exitFast: "var(--motion-exit-fast)",
    exit: "var(--motion-exit)",
    exitSlow: "var(--motion-exit-slow)",
    toggleFast: "var(--motion-toggle-fast)",
    toggle: "var(--motion-toggle)",
    toggleSlow: "var(--motion-toggle-slow)",
    pulseFast: "var(--motion-pulse-fast)",
    pulse: "var(--motion-pulse)",
    pulseSlow: "var(--motion-pulse-slow)",
  },
  shadow: {
    l1: "var(--shadow-l1)",
    l2: "var(--shadow-l2)",
    l3: "var(--shadow-l3)",
    l4: "var(--shadow-l4)",
    glowPositive: "var(--shadow-glow-positive)",
    glowBrand: "var(--shadow-glow-brand)",
    focusBrand: "var(--shadow-focus-brand)",
    focusNegative: "var(--shadow-focus-negative)",
    focusPositive: "var(--shadow-focus-positive)",
  },
} as const;

export type Tokens = typeof tokens;
